package br.com.taas.saas.gestaoproducao.platform.administration.audit.model;

public enum AuditAction {
    BOOTSTRAP_OWNER,
    TENANT_CREATED,
    TENANT_SUSPENDED,
    TENANT_REACTIVATED,
    TENANT_CLOSED,
    INVITATION_CREATED,
    INVITATION_ACCEPTED,
    INVITATION_REVOKED,
    INVITATION_EXPIRED,
    MEMBERSHIP_CREATED,
    MEMBERSHIP_ACTIVATED,
    MEMBERSHIP_REVOKED,
    PLATFORM_ADMIN_GRANTED,
    PLATFORM_ADMIN_REVOKED
}
